const employees = [
  "Abinaya",
  "Amal Suresh",
  "Anif",
  "Anirudhan",
  "Anitha S",
  "Arockiya Vinitha",
  "Arunmozhivarman",
  "Bharathi",
  "Boopathi M",
  "Danush Tom",
  "Esai Jothi",
  "Hariharan",
  "jayashree",
  "John Silas",
  "Kalyan",
  "kouser banu",
  "kamalesh P",
  "Krishna Raj",
  "krishnakumar c",
  "Keerthiga",
  "Madhuvanthiya",
  "Malavika",
  "Maria Swathi S",
  "Muthuselvi",
  "Meena",
  "Muthuramalingam",
  "Meganathan",
  "Muhammed Shiyahudheen",
  "Naveen( Placement)",
  "Paramesh",
  "Pavithra",
  "Preethika",
  "Prema",
  "Priya",
  "Premalatha",
  "Rajesh Selvaraj",
  "Rishikumar",
  "Ramanathan",
  "Rammesh",
  "Revanth",
  "Sagayamary",
  "Sangeetha R",
  "Saranya",
  "Selva",
  "Shanya",
  "Shebina X",
  "Sridevi Durga",
  "Sriram santhanam",
  "Subha",
  "Saishree",
  "Tamil Selvan",
  "Venkatesh P",
  "Venkteshan J",
  "Vinoth",
  "Vishnu Priya",
  "Viswajith",
  "Karthikraj"
]

const leaveTypes = [
  "permission",
  "casual leave",
  "halfday (1st)",
  "LOP",
  "halfday (2nd)"
]
